name: Python Linting & Testing

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: eks-runners

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install virtualenv
        virtualenv venv
        source venv/bin/activate
        pip3 install -r requirements.txt
    - name: Linting
      run: |
        . venv/bin/activate
        flake8 --exclude=venv* --statistics
    - name: Testing
      run: |
        . venv/bin/activate
        pytest -v --cov=.
    - name: Confirming
      run: |
          echo 'Test Complete'
          export
